// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/signup": {
    params: {};
  };
  "/auth/logout": {
    params: {};
  };
  "/auth/forgot-password": {
    params: {};
  };
  "/auth/reset-password": {
    params: {};
  };
  "/auth/confirm": {
    params: {};
  };
  "/auth/error": {
    params: {};
  };
  "/papers": {
    params: {};
  };
  "/papers/new": {
    params: {};
  };
  "/papers/:paperId": {
    params: {
      "paperId": string;
    };
  };
  "/papers/:paperId/publish": {
    params: {
      "paperId": string;
    };
  };
  "/papers/:paperId/new-version": {
    params: {
      "paperId": string;
    };
  };
  "/papers/:paperId/versions/:versionId": {
    params: {
      "paperId": string;
      "versionId": string;
    };
  };
  "/my-papers": {
    params: {};
  };
  "/review": {
    params: {};
  };
  "/profile/:userId": {
    params: {
      "userId": string;
    };
  };
  "/qna": {
    params: {};
  };
  "/qna/new": {
    params: {};
  };
  "/board": {
    params: {};
  };
  "/board/new": {
    params: {};
  };
  "/board/:postId": {
    params: {
      "postId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/auth/login" | "/auth/signup" | "/auth/logout" | "/auth/forgot-password" | "/auth/reset-password" | "/auth/confirm" | "/auth/error" | "/papers" | "/papers/new" | "/papers/:paperId" | "/papers/:paperId/publish" | "/papers/:paperId/new-version" | "/papers/:paperId/versions/:versionId" | "/my-papers" | "/review" | "/profile/:userId" | "/qna" | "/qna/new" | "/board" | "/board/new" | "/board/:postId";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/auth/login";
  };
  "routes/auth/signup.tsx": {
    id: "routes/auth/signup";
    page: "/auth/signup";
  };
  "routes/auth/logout.tsx": {
    id: "routes/auth/logout";
    page: "/auth/logout";
  };
  "routes/auth/forgot-password.tsx": {
    id: "routes/auth/forgot-password";
    page: "/auth/forgot-password";
  };
  "routes/auth/reset-password.tsx": {
    id: "routes/auth/reset-password";
    page: "/auth/reset-password";
  };
  "routes/auth/confirm.tsx": {
    id: "routes/auth/confirm";
    page: "/auth/confirm";
  };
  "routes/auth/error.tsx": {
    id: "routes/auth/error";
    page: "/auth/error";
  };
  "routes/papers.tsx": {
    id: "routes/papers";
    page: "/papers";
  };
  "routes/papers/new.tsx": {
    id: "routes/papers/new";
    page: "/papers/new";
  };
  "routes/papers/$paperId.tsx": {
    id: "routes/papers/$paperId";
    page: "/papers/:paperId";
  };
  "routes/papers/$paperId.publish.tsx": {
    id: "routes/papers/$paperId.publish";
    page: "/papers/:paperId/publish";
  };
  "routes/papers/$paperId.new-version.tsx": {
    id: "routes/papers/$paperId.new-version";
    page: "/papers/:paperId/new-version";
  };
  "routes/papers/$paperId.versions.$versionId.tsx": {
    id: "routes/papers/$paperId.versions.$versionId";
    page: "/papers/:paperId/versions/:versionId";
  };
  "routes/my-papers.tsx": {
    id: "routes/my-papers";
    page: "/my-papers";
  };
  "routes/review.tsx": {
    id: "routes/review";
    page: "/review";
  };
  "routes/profile/$userId.tsx": {
    id: "routes/profile/$userId";
    page: "/profile/:userId";
  };
  "routes/qna.tsx": {
    id: "routes/qna";
    page: "/qna";
  };
  "routes/qna/new.tsx": {
    id: "routes/qna/new";
    page: "/qna/new";
  };
  "routes/board.tsx": {
    id: "routes/board";
    page: "/board";
  };
  "routes/board/new.tsx": {
    id: "routes/board/new";
    page: "/board/new";
  };
  "routes/board/$postId.tsx": {
    id: "routes/board/$postId";
    page: "/board/:postId";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/auth/login": typeof import("./app/routes/auth/login.tsx");
  "routes/auth/signup": typeof import("./app/routes/auth/signup.tsx");
  "routes/auth/logout": typeof import("./app/routes/auth/logout.tsx");
  "routes/auth/forgot-password": typeof import("./app/routes/auth/forgot-password.tsx");
  "routes/auth/reset-password": typeof import("./app/routes/auth/reset-password.tsx");
  "routes/auth/confirm": typeof import("./app/routes/auth/confirm.tsx");
  "routes/auth/error": typeof import("./app/routes/auth/error.tsx");
  "routes/papers": typeof import("./app/routes/papers.tsx");
  "routes/papers/new": typeof import("./app/routes/papers/new.tsx");
  "routes/papers/$paperId": typeof import("./app/routes/papers/$paperId.tsx");
  "routes/papers/$paperId.publish": typeof import("./app/routes/papers/$paperId.publish.tsx");
  "routes/papers/$paperId.new-version": typeof import("./app/routes/papers/$paperId.new-version.tsx");
  "routes/papers/$paperId.versions.$versionId": typeof import("./app/routes/papers/$paperId.versions.$versionId.tsx");
  "routes/my-papers": typeof import("./app/routes/my-papers.tsx");
  "routes/review": typeof import("./app/routes/review.tsx");
  "routes/profile/$userId": typeof import("./app/routes/profile/$userId.tsx");
  "routes/qna": typeof import("./app/routes/qna.tsx");
  "routes/qna/new": typeof import("./app/routes/qna/new.tsx");
  "routes/board": typeof import("./app/routes/board.tsx");
  "routes/board/new": typeof import("./app/routes/board/new.tsx");
  "routes/board/$postId": typeof import("./app/routes/board/$postId.tsx");
};